<div class="left-group">
    <div class="group-title"><h1>Đăng nhập</h1></div>
    <div class="group-content">
        <p class="error"><?php echo $this->error;?></p>
        <form action="/auth/login" method="post">            
            <label for="username">Mã đơn hàng</label>
           <input type="text" name="username"/> 
            <input type="submit" value="Xem"/>
        </form>
    </div>
</div>