<table>

    <thead>
        <tr>
            <th>Tên phương tiện(Tiếng Việt)</th>
            <th>Tên phương tiện(Tiếng Việt)</th>
           
            <th>Thao tác</th>
          
        </tr>

    </thead>

    <tbody>
        <?php 
        $accounts = $this->accounts;
      
        
        foreach ($accounts as $a){
        ?>
        <tr>
       
          <td><?php echo $a['name'];?> </td>
          <td><?php echo $a['name_en'];?> </td>
     
          <td><a href='/admin/transport/edit/id/<?php echo $a['id']?>'>Sửa</a>
          <a class="delete" href='/admin/transport/del/id/<?php echo $a['id']?>'>Xóa</a></td>
        </tr>
        <?php  }?>       
    </tbody>
</table>
<div id="deleteDialog" style="display:none">
    <p>Bạn có chắc chắn muốn xóa không?</p>
</div>
<div style="margin-top: 20px;">
    <a class="button" href="/admin/transport/add">Thêm Phương tiện mới</a>
</div>