<table>

    <thead>
        <tr>
            <th>Tài khoản</th>
            <th>Email</th>
            <th>Thao tác</th>
            
            
        </tr>

    </thead>

    <tbody>
        <?php 
        $accounts = $this->accounts;
        foreach ($accounts as $a){
        ?>
        <tr>
            <td><?php echo $a['username'];?></td>
            <td><?php echo $a['email'];?></td>
            <td><a href='/admin/account/edit/id/<?php echo $a['id']?>'>Sửa</a>
            <a class = "delete" href='/admin/account/del/id/<?php echo $a['id']?>'>Xóa</a></td>
        </tr>
        <?php }?>       
    </tbody>
</table>
<div id="deleteDialog" style="display:none">
    <p>Bạn có chắc chắn muốn xóa không?</p>
</div>
<div style="margin-top: 20px;">
    <a class="button" href="/admin/acccount/add">Thêm Account mới</a>
</div>