<?php 
$lang = $this->lang;
$multi = $this->multilang;
?>
<div class="left-group">
    <div class="group-title"><h1><?php echo $multi['result_search_label']['name'.$lang];?></h1></div>
    <div class="group-content">
    <?php
    $tours = $this->tours;
    if($tours){
	    foreach ($tours as $t) {
	        ?>
	        <a href="/index/detail/id/<?php echo $t['id']; ?>">
	            <div class="inner_left">
  					<h3><?php echo $t['name_'.$lang]; ?></h3>
             
                    <img src="<?php echo $t['thumbnail_url']; ?>" class="tour-thumb"/>
             
                  

                    <p><b><?php echo $multi['during_label']['name'.$lang];?>: </b><?php $night =  $t['during_'.$lang];
	                    if($night!= floor($night)){
							echo $night." ".$multi['day_label']['name'.$lang];
						}else{
							$night = floor($night);
							$day = $night + 1;
							echo $day." ".$multi['day_label']['name'.$lang]." ".$night." ".$multi['night_label']['name'.$lang];

						}?></p>
                    <p><b><?php echo $multi['outward_label']['name'.$lang];?>: </b><?php echo $t['transport_outward_name_'.$lang]; ?></p>
                    <p><b><?php echo $multi['return_label']['name'.$lang];?>: </b><?php echo $t['transport_return_name_'.$lang]; ?></p>
                    <p><b><?php echo $multi['price_label']['name'.$lang];?>: </b><?php echo $t['price'];  ?> VND</p>

                

            </div>
	        </a>
	        <?php
	    }
    }
    else
    	echo "<div class='group-content'><div class='inner'><p>".$multi['error_2_label']['name'.$lang]."<p/></div></div>";
    ?>
    </div>
</div>
