<?php 
$lang = $this->lang;
$multi = $this->multilang;
?>
<div class="left-group">
    <div class="group-title"><h1></h1></div>
    <div class="group-content">
    <?php if($lang == ""){?>
       <iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dGtpaU5FNXFIMzVfWXRlWUlTd0hCNVE6MQ" width="760" height="678" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
       <?php }else{?>
       <iframe src="https://docs.google.com/spreadsheet/embeddedform?formkey=dHlpU2FvbE9RUXRUUUJXamtnTFk3S1E6MQ" width="760" height="678" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
       <?php } ?>
    </div>
</div>