<div class="left-group">
    <div class="group-title"><h1>Đăng ký thành viên</h1></div>
    <div class="group-content">
        <form action="/account/register" method="post">
            <label for="name">Họ và tên</label>
            <input type="text" name="name"/>
            <label for="username">Tên tài khoản</label>
            <input type="text" name="username"/>
            <label for="password">Mật khẩu</label>
            <input type="password" name="password"/>
            <label for="email">Email</label>
            <input type="text" name="email"/>
            <label for="cid_passport">Số CMND/Passport</label>
            <input type="text" name="cid_passport"/>
            <label for="phone">Điện thoại</label>
            <input type="text" name="phone"/>
            <label for="nation_id">Quốc tịch</label>
            <select name="nation_id">
                <option value=""></option>
            </select>
            <br/>
            <input type="submit" value="Đăng ký"/>
        </form>
    </div>
</div>